# File: hello-world-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world-app
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
        - name: hello-world-container
          image: nihalk11/hello-world-app:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
